name = "core-coalition"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
build = { command = "", cwd = "." }
```

Or easier — just create a `_redirects` file with this single line:
```
/* /index.html 200
